<?php require_once('layout/header.phtml')?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Película</title>
</head>
<body>
<form action="agregarPelicula" method="POST" enctype="multipart/form-data">
    <h1 class="form-h1">Agregar película:</h1>

    <label for="nombre">Nombre:</label>
    <input type="text" name="nombre" id="nombre" required><br><br>

    <label for="estreno">Fecha de estreno:</label>
    <input type="date" name="estreno" id="estreno" required><br><br>

    <label for="genero">Género:</label>
    <input type="text" name="genero" id="genero" required><br><br>


    <label for="director">Director:</label>
    <select name="director" id="director" required>
        <?php if (isset($directors) && is_array($directors)): ?>
            <?php foreach ($directors as $director): ?>
                <option value="<?= htmlspecialchars($director->id) ?>"><?= htmlspecialchars($director->nombre) ?></option>
            <?php endforeach; ?>
        <?php else: ?>
            <option value="">No directors available</option>
        <?php endif; ?>

    </select><br><br>
    <label for="descripcion">Descripción:</label>
    <textarea name="descripcion" id="descripcion" required></textarea><br><br>

    <label class="custom-file-upload" for="imageToUpload">Selecciona una imagen</label>
    <br><br>
    <input  type="file" name="input_name" id="imageToUpload" required>
    <input type="submit" value="Agregar Película">
</form>

<?php if (isset($_GET['mensaje'])): ?>
    <p><?php echo htmlspecialchars($_GET['mensaje']); ?></p>
<?php endif; ?>

<script src="../javascript/script.js"></script>
</body>
</html>