<?php require_once 'layout/header.phtml'; ?>
    <h1 class="ul-h1">Lista de directores</h1>

<ul class="ul-directors">
    <?php foreach ($directores as $director): ?>
        <li>
            <h2><?= htmlspecialchars($director->nombre) ?></h2>
            <div class="img-box">
                <img src="<?= htmlspecialchars($director->imagen) ?>" alt="Imagen del director">
            </div>
            <a href="verPeliculasDirector/<?= $director->id ?>" class="a-animation">Ver películas</a>

            <?php if (isset($_SESSION['ID_USER'])): ?>
                <a href="eliminarDirector/<?= $director->id ?>" class="a-animation">Borrar</a>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>


</ul>
<?php if (isset($_SESSION['ID_USER'])):
    require_once 'templates/form.add.director.phtml';
endif; ?>