<?php
require_once 'templates/layout/header.phtml'
?>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Películas de <?php echo htmlspecialchars($director->nombre); ?></title>
</head>
<body>
    <h1 class="ul-h1">Películas de <?php echo htmlspecialchars($director->nombre); ?></h1>
    <ul class="ul-individual-director">
        <?php foreach ($peliculas as $pelicula): ?>
            <li>
                <a class="a-animation" href="pelicula/<?php echo htmlspecialchars($pelicula->id); ?>"><?php echo htmlspecialchars($pelicula->nombre); ?></a>
                <p>Fecha de estreno: <?php echo htmlspecialchars($pelicula->fecha_estreno); ?></p>
                <p>Género: <?php echo htmlspecialchars($pelicula->genero); ?></p>
            </li>
        <?php endforeach; ?>
    </ul>
    <?php if (isset($_SESSION['ID_USER'])): ?>

        <form action="editarDirector/<?php echo $director->id; ?>" method="POST">
        <h1 class="form-h1">Editar Director</h1>

        <label for="nombre">Editar nombre:</label>
        <input type="text" id="nombre" name="nombre">

        <button type="submit">Actualizar nombre</button>
    </form>
    <?php endif; ?>



</body>
</html>
