<?php require('layout/header.phtml') ?>
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalles de la Película</title>
</head>
<body>
<h1 class="film-h1"><?= htmlspecialchars($film->nombre) ?></h1>

<div class="film-box">

    <div class="film-container">
        <div class="film-photo">
            <img src="<?= htmlspecialchars($film->imagen) ?>" alt="film-photo">
        </div>
        <div class="film-details">
            <?php if (isset($film)): ?>
                <table>
                    <tr>
                        <th>ID</th>
                        <td><?= htmlspecialchars($film->id) ?></td>
                    </tr>
                    <tr>
                        <th>Título</th>
                        <td><?= htmlspecialchars($film->nombre) ?></td>
                    </tr>
                    <tr>
                        <th>Género</th>
                        <td><?= htmlspecialchars($film->genero) ?></td>
                    </tr>
                    <tr>
                        <th>Director</th>
                        <td>
                            <a class="a-animation" href="<?= BASE_URL . '/verPeliculasDirector/' . htmlspecialchars($film->id_director) ?>">
                                <?= htmlspecialchars($film->director_nombre) ?>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <th>Estreno</th>
                        <td><?= htmlspecialchars($film->fecha_estreno) ?></td>
                    </tr>
                    <tr class="tr-description">
                        <th>Descripción</th>
                        <td class="description">
                            <button id="toggleDescriptionBtn">Ver descripción</button>
                            <div id="descriptionContent" class="description-text hidden">
                                <?= htmlspecialchars($film->descripcion) ?>
                            </div>
                        </td>
                    </tr>

                </table>
            <?php else: ?>
                <p>No se encontraron detalles de la película.</p>
            <?php endif; ?>
        </div>
    </div>
</div>
<?php if (isset($_SESSION['ID_USER'])): ?>
    <a href="eliminarPelicula/<?= $film->id ?>" class="a-animation">Borrar</a>
    <?php require_once 'templates/form.edit.film.phtml' ?>
<?php endif; ?>
<script src="./javascript/script.js"></script>


</body>
</html>