<?php require 'layout/header.phtml' ?>
<?php //require '/layout/footer.phtml' ?>



<h1>
    <?php
        if (isset($_SESSION['USERNAME_USER']) && !empty($_SESSION['USERNAME_USER'])) {
            echo 'Bienvenido ' . $_SESSION['USERNAME_USER'];
        }
        elseif (isset($_SESSION['EMAIL_USER']) && !empty($_SESSION['EMAIL_USER'])) {
            echo 'Bienvenido ' . $_SESSION['EMAIL_USER'];
        }
    ?>
</h1>
<ul class="film-list-ul">
    <?php foreach($films as $film): ?>
        <li class="film-name-box">
            <a href="pelicula/<?= $film->id ?>">
                <img src="<?= $film->imagen ?>" width="200" alt="<?= htmlspecialchars($film->nombre) ?>">
            </a>
            <a href="pelicula/<?= $film->id ?>">
                <h2><?= htmlspecialchars($film->nombre) ?></h2>
            </a>
        </li>
    <?php endforeach ?>
</ul>
