<?php require_once 'layout/header.phtml'; ?>

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agregar Director</title>
</head>
<body>


<?php if (isset($_SESSION['ID_USER'])): ?>
    <form action="agregarDirector" method="POST" enctype="multipart/form-data">
        <h1 class="form-h1">Agregar Director</h1>

        <label for="nombre">Nombre:</label>
        <input type="text" name="nombre" id="nombre" required><br><br>
        <h2>Imagen del director:</h2>
        <label class="custom-file-upload" for="imageToUpload">Selecciona una imagen</label>
        <input type="file" name="input_name" id="imageToUpload" required>

        <input type="submit" value="Agregar Director">
    </form>
<?php else: ?>
    <p>Debes estar logueado para agregar un director.</p>
<?php endif; ?>
</body>
</html>