

<?php require 'templates/layout/header.phtml' ?>




<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

    <form method='post' action='login'>
        <div class='form-group'>
            <label for='identifier'>Email o Username</label>
            <input type='text' class='form-control' id='identifier' name='identifier' required>
        </div>
        <div class='form-group'>
            <label for='password'>Contraseña</label>
            <input type='password' class='form-control' id='password' name='password' required>
        </div>
        <button type='submit' class='btn btn-primary'>Ingresar</button>
    </form>

<?php //require 'templates/layout/footer.phtml' ?>